import React, { useEffect, useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, Alert, ScrollView } from 'react-native';
import API from '../api/client';
import { Screen, Card, SectionTitle, colors, money } from '../components/UI';

export default function SaleReturnScreen({route,navigation}){
 const saleId=route.params?.saleId; const [sale,setSale]=useState(null),[qtys,setQtys]=useState({}),[refund,setRefund]=useState('0'),[reason,setReason]=useState('Customer return'),[saving,setSaving]=useState(false);
 useEffect(()=>{API.get(`/sales/${saleId}`).then(r=>{setSale(r.data);const m={};(r.data.items||[]).forEach(i=>{const returned=(r.data.returnItems||[]).filter(x=>Number(x.sale_item_id)===Number(i.id)).reduce((a,x)=>a+Number(x.qty||0),0);m[i.id]=String(Math.max(0,Number(i.qty)-returned))});setQtys(m)}).catch(e=>Alert.alert('Could not load sale',e.message))},[saleId]);
 if(!sale)return <Screen><Text>Loading…</Text></Screen>;
 const selected=(sale.items||[]).map(i=>({...i,returnQty:Number(qtys[i.id]||0)})).filter(i=>i.returnQty>0); const total=selected.reduce((a,i)=>a+i.returnQty*Number(i.unit_price||0),0);
 const submit=async()=>{if(!selected.length)return Alert.alert('Return','Enter at least one return quantity');if(Number(refund)>total)return Alert.alert('Return','Refund cannot exceed return value');setSaving(true);try{await API.post(`/sales/${sale.id}/return`,{items:selected.map(i=>({sale_item_id:i.id,qty:i.returnQty})),refund_amount:Number(refund),reason});Alert.alert('Return posted','Stock has been restored',[{text:'OK',onPress:()=>navigation.goBack()}])}catch(e){Alert.alert('Could not post return',e.message)}finally{setSaving(false)}};
 return <Screen scroll><SectionTitle>Customer Return — {sale.invoice_no}</SectionTitle>{selected.length>0&&<Card><Text style={styles.total}>Return Value {money(total)}</Text></Card>}{(sale.items||[]).map(i=><Card key={i.id}><Text style={styles.name}>{i.medicine_name}</Text><Text style={styles.meta}>Batch {i.batch_no} · Sold {i.qty}</Text><TextInput keyboardType="decimal-pad" style={styles.input} value={qtys[i.id]||'0'} onChangeText={v=>setQtys(x=>({...x,[i.id]:v}))} placeholder="Return quantity" /></Card>)}<TextInput style={styles.input} value={reason} onChangeText={setReason} placeholder="Reason"/><TextInput keyboardType="decimal-pad" style={styles.input} value={refund} onChangeText={setRefund} placeholder="Refund amount"/><TouchableOpacity disabled={saving} style={styles.button} onPress={submit}><Text style={styles.buttonText}>{saving?'Posting…':'Post Return'}</Text></TouchableOpacity></Screen>;
}
const styles=StyleSheet.create({name:{fontWeight:'800',fontSize:16},meta:{color:colors.muted,marginTop:3},input:{borderWidth:1,borderColor:colors.border,borderRadius:10,paddingHorizontal:12,paddingVertical:11,marginTop:10},button:{backgroundColor:colors.primary,borderRadius:10,paddingVertical:14,alignItems:'center',marginTop:14},buttonText:{color:'#fff',fontWeight:'800'},total:{fontWeight:'800',fontSize:16}});
